export const enum Pages {
  DEFAULT = 'DEFAULT',
  MAIN = 'MAIN',
  AUTH = 'AUTH',
  CATALOG_MAIN = 'CATALOG_MAIN',
  PRODUCT_GROUPS_MAIN = 'PRODUCT_GROUPS_MAIN',
  PROFILE_MAIN = 'PROFILE_MAIN',
  DASHBOARD_MAIN = 'DASHBOARD_MAIN',
  CATEGORIES_MAIN = 'CATEGORIES_MAIN',
  USERS_MAIN = 'USERS_MAIN',
}
