export const enum Pages {
  MAIN = 'MAIN',
  AUTH = 'AUTH',
  CATALOG = 'CATALOG',
  PRODUCT_GROUPS = 'PRODUCT_GROUPS',
  PROFILE = 'PROFILE',
  DASHBOARD = 'DASHBOARD',
  CATEGORIES = 'CATEGORIES',
}
